ai-cfia/ailab-datastore

- datastore/__init__.py
- datastore/db/__init__.py
- datastore/db/metadata/inference/__init__.py
- datastore/db/queries/inference/__init__.py
- doc/datastore.md
- doc/inference-feedback.md
- tests/inference_feedback_correction.json
- tests/inference_feedback_perfect.json
- tests/ml_structure_exemple.json
- tests/test_datastore.py
- tests/test_db.py
> Issue #40: Implement Correction feedback function for inferences

- datastore/__init__.py
> fix box field issue #48

- .gitignore
- datastore/bin/new_user.py
- datastore/db/bytebase/schema_nachet_0.0.11.sql
- datastore/db/bytebase/trigger_inference_verification.sql
> Issue #41 : Create SQL verified_inference_trigger

- doc/datastore.md
- doc/fertiScan-architecture.md
- doc/nachet-architecture.md
Issue https://github.com/ai-cfia/nachet-datastore/issues/51
> Issue #51 update repo doc to integrate fertiscan

- datastore/__init__.py
- datastore/blob/azure_storage_api/__init__.py
- datastore/db/bytebase/delete-on-cascade.sql
- datastore/db/bytebase/schema_nachet_0.0.11.sql
- datastore/db/queries/picture/__init__.py
- doc/nachet-manage-folders.md
- tests/test_azure_storage.py
- tests/test_datastore.py
- tests/test_db.py
> 63 rework the delete of a folder to save for training

- pyproject.toml
> pyproject update

- datastore/bin/ml-import.py
- datastore/db/queries/machine_learning/__init__.py
- datastore/nachet/__init__.py
> 94 add a test pipeline

- datastore/nachet/__init__.py
- tests/nachet/db/test_inference.py
ref https://github.com/ai-cfia/nachet-backend/issues/98
> Update batch upload to work around seed id

- datastore/db/metadata/inference/__init__.py
- tests/nachet/test_datastore.py
> use pydantic to rebuild inference

- datastore/db/metadata/inference/__init__.py
- datastore/db/queries/inference/__init__.py
- datastore/nachet/__init__.py
- tests/nachet/test_datastore.py
ref https://github.com/ai-cfia/nachet-backend/issues/119
> get_inference by inference_id

- .gitignore
- datastore/db/bytebase/FertiScan/new_inspection_function.sql
- datastore/db/bytebase/FertiScan/schema_0.0.10.sql
- datastore/db/bytebase/FertiScan/update_inspection_function.sql
- tests/fertiscan/db/update_inspection/test_update_inspection.py
> issue #115: handle empty, null or missing organization info

- pyproject.toml
> issue #123: fix ImportError while using the package in Fertiscan Backend

- datastore/db/metadata/inspection/__init__.py
> issue #125: use .get to avoid keyerror

- datastore/db/bytebase/FertiScan/new_inspection_function.sql
- datastore/db/bytebase/FertiScan/schema_0.0.12.sql
- datastore/db/bytebase/FertiScan/update_inspection_function.sql
- datastore/db/queries/inspection/__init__.py
- tests/fertiscan/test_datastore.py
> 132 decouple olap schema from oltp schema to prevent referential integrity issues

- datastore/db/metadata/inspection/__init__.py
- tests/fertiscan/metadata/test_inspection.py
> Improve None values handling in Inpection models

- datastore/db/bytebase/FertiScan/new_inspection/new_guaranteed_analysis.sql
- datastore/db/bytebase/FertiScan/new_inspection/new_ingredient.sql
- datastore/db/bytebase/FertiScan/new_inspection/new_metric_unit.sql
- datastore/db/bytebase/FertiScan/new_inspection/new_micronutrient.sql
- datastore/db/bytebase/FertiScan/new_inspection/new_organization_located.sql
- datastore/db/bytebase/FertiScan/new_inspection/new_specification.sql
- datastore/db/bytebase/FertiScan/new_inspection_function.sql
- datastore/db/bytebase/FertiScan/schema_0.0.12.sql
- datastore/db/bytebase/FertiScan/update_inspection_function.sql
- datastore/db/metadata/inspection/__init__.py
- datastore/db/queries/organization/__init__.py
- datastore/db/queries/sub_label/__init__.py
- db-creation.py
- tests/fertiscan/db/test_ingredient.py
- tests/fertiscan/db/test_metric.py
- tests/fertiscan/db/test_nutrients.py
- tests/fertiscan/db/test_organization.py
- tests/fertiscan/db/test_specification.py
- tests/fertiscan/db/test_sub_label.py
- tests/fertiscan/test_datastore.py
> Issue #146: remove NotNull constraint

- datastore/db/bytebase/FertiScan/init_data.sql
- datastore/db/bytebase/FertiScan/schema_0.0.6.sql
> Issue #165: fix table for inserts

- .github/workflows/publish-package.yml
Offers cleaner way to reference to the package from backends thats compatible with renovate bot
> Adds a release branch from which we create tag

- datastore/doc/bytebase-doc.md
> Issue #135: refer Bytebase doc to dev-rel-docs

- fertiscan_pyproject.toml
- tests/fertiscan/metadata/test_inspection.py
This PR adds test to confirm #176 is patched
> 176 as a dev i want company fields to be correctly persisted during analysis registration

- datastore/__init__.py
- datastore/bin/upload_picture_set.py
- datastore/db/metadata/picture_set/__init__.py
- datastore/db/queries/picture/__init__.py
- fertiscan/__init__.py
- fertiscan_pyproject.toml
- nachet/__init__.py
- nachet/bin/deployment_mass_import.py
- nachet_pyproject.toml
- tests/fertiscan/db/test_inspection.py
- tests/nachet/db/test_inference.py
- tests/nachet/db/test_picture.py
- tests/test_db.py
- tests/test_metadata.py
> Issue #127: remove redundant call

- fertiscan/__init__.py
- fertiscan/db/metadata/inspection/__init__.py
- fertiscan/db/queries/inspection/__init__.py
- fertiscan_pyproject.toml
- tests/fertiscan/metadata/test_inspection.py
- tests/fertiscan/test_datastore.py
> Issue #202: Remove label_id from `build_inspection_export()`

- .github/workflows/project-issue-status.yml
> issue #219: testing python-lint workflow + added issue status workflow

- fertiscan/db/metadata/inspection/__init__.py
- fertiscan_pyproject.toml
- tests/fertiscan/metadata/test_inspection.py
> issue #239: return ingredients list when record_keeping is false

- fertiscan/db/metadata/inspection/__init__.py
- fertiscan_pyproject.toml
- tests/fertiscan/analyse.json
- tests/fertiscan/inspection.json
- tests/fertiscan/inspection_export.json
- tests/fertiscan/metadata/test_inspection.py
- tests/fertiscan/test_datastore.py
The handling was already down in the schema.
> issue #242: handle `is_minimal`

- datastore/__init__.py
- datastore/db/metadata/picture_set/__init__.py
- datastore/db/queries/container/__init__.py
- datastore/db/queries/group/__init__.py
- datastore/db/queries/user/__init__.py
- datastore/doc/Access-policies.md
- datastore/doc/datastore.md
- nachet/__init__.py
- nachet/db/bytebase/schema_0.1.1.sql
- nachet/db/metadata/picture/__init__.py
- tests/test_datastore.py
- tests/test_db.py
> 33 create the Access Control structure (Role & Permissions)

- fertiscan/__init__.py
- fertiscan/db/metadata/inspection/__init__.py
- fertiscan/db/queries/errors.py
- fertiscan/db/queries/fertilizer/__init__.py
- fertiscan/db/queries/ingredient/__init__.py
- fertiscan/db/queries/inspection/__init__.py
- fertiscan/db/queries/label/__init__.py
- fertiscan/db/queries/metric/__init__.py
- fertiscan/db/queries/nutrients/__init__.py
- fertiscan/db/queries/organization/__init__.py
- fertiscan/db/queries/registration_number/__init__.py
- fertiscan/db/queries/sub_label/__init__.py
- tests/fertiscan/db/test_guaranteed_analysis.py
- tests/fertiscan/db/test_ingredient.py
- tests/fertiscan/db/test_inspection.py
- tests/fertiscan/db/test_label.py
- tests/fertiscan/db/test_metric.py
- tests/fertiscan/db/test_organization.py
- tests/fertiscan/db/test_registration_number.py
- tests/fertiscan/db/test_sub_label.py
- tests/fertiscan/test_datastore.py
https://github.com/ai-cfia/ailab-datastore/issues/249
> 249-fertiscan-as-a-dev-i-want-to-move-heavy-db-functions-to-the-backend-for-better-performance-and-scalability
